services:
  nextjs:
    image: node:18
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: ["sh", "-c", "npm run build && npm start"]
    environment:
      - NODE_ENV=production